### ISSUE TITLE
`seaborn 0.12.x` breaks plotting functionality

### ISSUE THREAD

**Issue by dennisbrookner** [rs-station/rs-booster#36]
I'm still in the process of figuring out what changed, and subsequently, whether we can change our code to continue with the state-of-the-art seaborn API. In the interim, we should just pin the required seaborn version to `<=0.11.2`. This is the traceback:
```
Traceback (most recent call last):
  File "/n/hekstra_lab/people/brookner/miniconda3/envs/rs/bin/rs.ccsym", line 8, in <module>
    sys.exit(main())
  File "/n/hekstra_lab/people/brookner/miniconda3/envs/rs/lib/python3.9/site-packages/rsbooster/stats/ccsym.py", line 144, in main
    sns.lineplot(
  File "/n/hekstra_lab/people/brookner/miniconda3/envs/rs/lib/python3.9/site-packages/seaborn/relational.py", line 645, in lineplot
    p.plot(ax, kwargs)
  File "/n/hekstra_lab/people/brookner/miniconda3/envs/rs/lib/python3.9/site-packages/seaborn/relational.py", line 489, in plot
    func(
  File "/n/hekstra_lab/people/brookner/miniconda3/envs/rs/lib/python3.9/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/n/hekstra_lab/people/brookner/miniconda3/envs/rs/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5245, in fill_between
    return self._fill_between_x_or_y(
  File "/n/hekstra_lab/people/brookner/miniconda3/envs/rs/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5150, in _fill_between_x_or_y
    ind, dep1, dep2 = map(
  File "/n/hekstra_lab/people/brookner/miniconda3/envs/rs/lib/python3.9/site-packages/numpy/ma/core.py", line 2366, in masked_invalid
    condition = ~(np.isfinite(a))
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
I've only encountered this with `rs.ccsym`, but I bet this is the case for any `rs-booster` function that makes a `seaborn` plot.

Unrelatedly, we also get the following `FutureWarning`:
```
/n/hekstra_lab/people/brookner/miniconda3/envs/rs/lib/python3.9/site-packages/rsbooster/stats/ccsym.py:144: FutureWarning: 

The `ci` parameter is deprecated. Use `errorbar='sd'` for the same effect.
```
which is easily fixable.

**Comment by dennisbrookner** [comment]
IMO, it feels increasingly nonfeasible for `rs-booster` to live without a test suite of some kind. This bug is an example of the kind of thing that'll probably happen all the time!

**Comment by dennisbrookner** [comment]
Thanks to the heroic efforts of Ian, I've identified the underlying issue as relating to how pandas custom dtypes behave when coerced into numpy. I'll provide more details here on Monday.

**Comment by dennisbrookner** [comment]
Here is the relevant issue in `pandas`:
https://github.com/pandas-dev/pandas/issues/48891
so this is a known issue, but unclear that it will be fixed anytime soon. If it's a long-term thing, `seaborn` should probably work around it... in the mean time, we should just pin the `seaborn` version and call it a day.

**Comment by dennisbrookner** [comment]
This issue has now been worked around, and the associated PR #37 has been closed.
