### ISSUE TITLE
rs.scaleit fails on concat operation

### ISSUE THREAD

**Issue by DHekstra** [rs-station/rs-booster#39]
When scaling two merged MTZs (off, on conditions) using rs.scaleit, I run into two difficulties.

1. A warning of a divide by zero issue. Probably not a big deal.
2. An error: "Reindexing only valid with uniquely valued Index objects" upon the rs.concat call on line 142 of scaleit.py.

MTZ files here: https://drive.google.com/drive/folders/1siS3y_T6210lLwNGAcGFUnkduOmT-TTt?usp=sharing

traceback:
`/n/home12/dhekstra/miniconda3/envs/careless-dw-8/lib/python3.10/site-packages/reciprocalspaceship/algorithms/scale_merged_intensities.py:63: RuntimeWarning: divide by zero encountered in log
  logJ = np.nan_to_num(np.log(J), -np.inf)
/n/home12/dhekstra/miniconda3/envs/careless-dw-8/lib/python3.10/site-packages/reciprocalspaceship/algorithms/scale_merged_intensities.py:64: RuntimeWarning: divide by zero encountered in log
  log_prefactor = np.log(Jmax - Jmin) - np.log(2.0)
/n/home12/dhekstra/miniconda3/envs/careless-dw-8/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py:2126: RuntimeWarning: invalid value encountered in divide
  x = np.asarray((x - loc)/scale, dtype=dtyp)
/n/home12/dhekstra/miniconda3/envs/careless-dw-8/lib/python3.10/site-packages/reciprocalspaceship/algorithms/scale_merged_intensities.py:83: RuntimeWarning: overflow encountered in multiply
  + logsumexp(logweights + 2.0 * logJ + logP + logL - logZ[:, None], axis=1)
/n/home12/dhekstra/miniconda3/envs/careless-dw-8/lib/python3.10/site-packages/reciprocalspaceship/algorithms/scale_merged_intensities.py:83: RuntimeWarning: invalid value encountered in add
  + logsumexp(logweights + 2.0 * logJ + logP + logL - logZ[:, None], axis=1)
Number of common reflections: 10762
Traceback (most recent call last):
  File "/n/home12/dhekstra/miniconda3/envs/careless-dw-8/bin/rs.scaleit", line 33, in <module>
    sys.exit(load_entry_point('rs-booster', 'console_scripts', 'rs.scaleit')())
  File "/n/home12/dhekstra/ipython_notebooks/rs-booster/rsbooster/scaleit/scaleit.py", line 142, in main
    joined = rs.concat([ref.loc[common]] + mtzs, axis=1)
  File "/n/home12/dhekstra/miniconda3/envs/careless-dw-8/lib/python3.10/site-packages/reciprocalspaceship/concat.py", line 39, in concat
    result = pd.concat(*args, **kwargs)
  File "/n/home12/dhekstra/miniconda3/envs/careless-dw-8/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/n/home12/dhekstra/miniconda3/envs/careless-dw-8/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 360, in concat
    return op.get_result()
  File "/n/home12/dhekstra/miniconda3/envs/careless-dw-8/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 591, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "/n/home12/dhekstra/miniconda3/envs/careless-dw-8/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3729, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects`

**Comment by DHekstra** [comment]
I'm going to close this issue as it has not resurfaced.
